exclude_paths:
  # Configuration Files
  - "**/*.{yml,yaml}"
  - "**/.codeconcat.yml"
  - "**/.github/*.{yml,yaml}"

  # Test files
  - "**/tests/**"
  - "**/test_*.py"
  - "**/*_test.py"

  # Build and cache files
  - "**/build/**"
  - "**/dist/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/*.pyd"
  - "**/.pytest_cache/**"
  - "**/.coverage"
  - "**/htmlcov/**"

  # Version control
  - "**/.git/**"
  - "**/.gitignore"
  - "**/.gitattributes"

  # Environment and dependencies
  - "**/.env"
  - "**/.venv/**"
  - "**/env/**"
  - "**/venv/**"
  - "**/node_modules/**"
  
  # IDE and editor files
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/*.swp"
  - "**/*.swo"

  # Documentation
  - "**/docs/_build/**"
  - "**/.docstring/**"

  # CodeConCat Output
  - "**/code_concat_output.md"

include_paths:
  - "**/*.{py,js,ts,jsx,tsx,java,cpp,c,h,hpp,go,rs,rb,php}"
  - "**/*.{md,rst,txt}"
  - "**/LICENSE*"
  - "**/README*"

# Display Options
include_file_summary: true
include_directory_structure: true
remove_comments: true
remove_empty_lines: true
show_line_numbers: true
