################################################################################
# CodeConCat – project configuration
# Tip: run `codeconcat . --show-config` to view the final merged config.
################################################################################

########################
#  PATH FILTERING
########################
# 1. Any path matching `exclude_paths` is ignored.
# 2. If `include_paths` is NOT empty, a file must match at least one of them.
# 3. If `include_languages` is NOT empty, the file’s detected language
#    (per ext_map) must appear in the list.

exclude_paths:
  ## Version‑control metadata
  - ".git/"
  - "**/.git/**"
  - ".gitignore"
  - ".gitmodules"

  ## Build artefacts / dependency dirs
  - "node_modules/"
  - "**/node_modules/**"
  - "dist/"
  - "**/dist/**"
  - "build/"
  - "**/build/**"
  - ".next/"
  - "**/.next/**"
  - "**/__pycache__/**"

  ## IDE/editor clutter
  - ".vscode/**"
  - ".idea/**"
  - "**/*.swp"
  - "**/*.swo"

  ## Test artefacts & coverage
  - "coverage/"
  - "**/coverage/**"
  - ".pytest_cache"
  - "**/tests/**"
  - "**/test/**"
  - "**/*_test.*"
  - "**/*.test.*"
  - "**/*.spec.*"

  ## Docs, assets, binaries
  - "docs/"
  - "**/docs/**"
  - "**/*.md"
  - "**/README*"
  - "**/LICENSE*"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.svg"
  - "**/*.ico"
  - "**/*.pdf"
  - "**/*.ttf"
  - "**/*.woff"
  - "**/*.woff2"
  - "**/*.eot"
  - "**/*.zip"
  - "**/*.tar.gz"
  - "**/*.tgz"

  ## Generated / minified bundles
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/*.bundle.js"
  - "**/*.bundle.css"
  - "**/*.chunk.js"
  - "**/*.chunk.css"
  - "**/manifest.json"

  ## Environment / secrets / venvs
  - ".env"
  - "**/.env"
  - "**/.env.*"
  - ".venv/"
  - "venv/"
  - "**/.venv/**"
  - "**/venv/**"
  - "*env"            # generic env dir (e.g. `env/`)

include_paths:
  # ── Front‑end / full‑stack JS & TS ───────────────────────────────────────────
  - "src/**/*.ts"
  - "src/**/*.tsx"
  - "src/**/*.js"
  - "src/**/*.jsx"

  - "app/**/*.ts"
  - "app/**/*.tsx"
  - "app/**/*.js"
  - "app/**/*.jsx"

  - "components/**/*.ts"
  - "components/**/*.tsx"
  - "components/**/*.js"
  - "components/**/*.jsx"

  - "lib/**/*.ts"
  - "lib/**/*.tsx"
  - "lib/**/*.js"
  - "lib/**/*.jsx"

  # ── Python source code ───────────────────────────────────────────────────────
  - "**/*.py"

  # ── Project‑root metadata ───────────────────────────────────────────────────
  - "package.json"
  - "pyproject.toml"

include_languages:           # must match ext_map() outputs
  - python
  - javascript
  - typescript
  - r
  - py
  - js
  - tsx

########################
#  FEATURE TOGGLES
########################
enable_docs:         false   # pull in standalone docs (.md, .rst, etc.)
merge_docs:          false   # merge docs into main output
enable_ai_context:   true    # prepend AI‑friendly “preamble”
enable_annotations:  true    # run LLM annotator
disable_symbols:     false   # skip symbol index when true
remove_docstrings:   true

########################
#  DISPLAY OPTIONS
########################
include_file_summary:        true
include_directory_structure: true
remove_comments:             true
remove_empty_lines:          true
show_line_numbers:           true

########################
#  EXECUTION CONTROLS
########################
max_workers: 4               # thread‑pool size (null = automatic)

########################
#  OUTPUT
########################
output:        output.md     # final file or base name when splitting
format:        markdown      # markdown | json | xml
split_output:  1             # >1 → split Markdown into N parts
sort_files:    true          # alphabetical inside the output