exclude_paths:
  # Next.js build artifacts and configuration
  - "**/.next/**"  # Exclude all .next directory contents
  - "**/next-env.d.ts"
  - "**/next.config.*"
  - "**/postcss.config.*"
  - "**/tailwind.config.*"
  - "**/*.tsbuildinfo"
  
  # Build artifacts and chunks
  - "**/static/chunks/**"
  - "**/server/chunks/**"
  - "**/_next/**"
  - "**/webpack-runtime.*"
  - "**/webpack.*"
  - "**/server-reference-manifest.*"
  - "**/middleware-manifest.*"
  - "**/client-reference-manifest.*"
  - "**/BUILD_ID"
  - "**/trace"
  - "**/*.js.map"
  - "**/*.css.map"
  - "**/*.rsc"
  - "**/*.meta"
  - "**/*.nft.json"
  
  # Node modules and package files
  - "**/node_modules/**"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/.yarn/**"
  - "**/.pnp.*"
  
  # Build directories and caches
  - "**/cache/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.turbo/**"
  - "**/.swc/**"
  - "**/.eslintcache"
  - "**/.tsbuildinfo"
  
  # Version control
  - "**/.git/**"
  - "**/.gitignore"
  - "**/.gitmodules"
  
  # Environment and local files
  - "**/.env*"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  
  # IDE and editor files
  - "**/.vscode/**"
  - "**/.idea/**"
  - "**/*.swp"
  
  # Test files
  - "**/tests/**"
  - "**/test/**"
  - "**/*_test.*"
  - "**/*.test.*"
  - "**/*.spec.*"
  
  # Documentation
  - "**/docs/**"
  - "**/doc/**"
  - "**/*.md"
  - "**/README*"
  - "**/LICENSE*"
  
  # Non-code assets
  - "**/*.svg"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.ico"
  - "**/*.woff"
  - "**/*.woff2"
  - "**/*.ttf"
  - "**/*.eot"
  - "**/*.pdf"
  - "**/*.zip"
  - "**/*.tar.gz"
  - "**/*.tgz"
  
  # Generated and temporary files
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/*.bundle.js"
  - "**/*.bundle.css"
  - "**/*.chunk.js"
  - "**/*.chunk.css"
  - "**/manifest.json"

include_languages:
  - typescript
  - javascript
  - python
  - tsx
  - jsx

include_paths:
  # Source code
  - "**/src/**/*.ts"
  - "**/src/**/*.tsx"
  - "**/src/**/*.js"
  - "**/src/**/*.jsx"
  - "**/src/**/*.py"
  
  # App directory (Next.js)
  - "**/app/**/*.ts"
  - "**/app/**/*.tsx"
  - "**/app/**/*.js"
  - "**/app/**/*.jsx"
  
  # Components
  - "**/components/**/*.ts"
  - "**/components/**/*.tsx"
  - "**/components/**/*.js"
  - "**/components/**/*.jsx"
  
  # Library code
  - "**/lib/**/*.ts"
  - "**/lib/**/*.tsx"
  - "**/lib/**/*.js"
  - "**/lib/**/*.jsx"
  
  # Package configuration (but not lock files)
  - "**/package.json"

# Display Options
include_file_summary: true
include_directory_structure: true
remove_comments: true
remove_empty_lines: true
show_line_numbers: true
