exclude_paths:
  # Configuration Files
  - "*.yml"
  - "./*.yml"
  - "**/*.yml"
  - "*.yaml"
  - "./*.yaml"
  - "**/*.yaml"
  - ".codeconcat.yml"
  - "./.codeconcat.yml"
  - "**/.codeconcat.yml"
  - ".github/*.yml"
  - ".github/*.yaml"
  - "**/.github/*.yml"
  - "**/.github/*.yaml"

  # Test files - be very specific and thorough
  - "tests"
  - "./tests"
  - "tests/"
  - "./tests/"
  - "tests/**"
  - "./tests/**"
  - "tests/**/*"
  - "./tests/**/*"
  - "**/tests"
  - "**/tests/"
  - "**/tests/**"
  - "**/tests/**/*"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/test_*.py[cod]"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/test_*.py[cod]"
  - "test_*.py"
  - "*_test.py"
  - "./test_*.py"
  - "./*_test.py"
  - "**/test_*.py"
  - "**/*_test.py"

  # Log files - be very thorough
  - "*.log"
  - "./*.log"
  - "**/*.log"
  - "**/leap.log"
  - "**/sqm.log"
  - "**/timer.log"
  - "**/build.log"
  - "**/test.log"
  - "**/debug.log"
  - "**/error.log"
  - "leap.log"
  - "sqm.log"
  - "timer.log"
  - "build.log"
  - "test.log"
  - "debug.log"
  - "error.log"
  - "./leap.log"
  - "./sqm.log"
  - "./timer.log"
  - "./build.log"
  - "./test.log"
  - "./debug.log"
  - "./error.log"

  # Build and package files - be very aggressive
  - "build"
  - "./build"
  - "build/"
  - "./build/"
  - "build/**"
  - "./build/**"
  - "build/**/*"
  - "./build/**/*"
  - "**/build"
  - "**/build/"
  - "**/build/**"
  - "**/build/**/*"
  - "*.egg-info"
  - "./*.egg-info"
  - "*.egg-info/"
  - "./*.egg-info/"
  - "*.egg-info/**"
  - "./*.egg-info/**"
  - "*.egg-info/**/*"
  - "./*.egg-info/**/*"
  - "**/*.egg-info"
  - "**/*.egg-info/"
  - "**/*.egg-info/**"
  - "**/*.egg-info/**/*"
  - "__pycache__"
  - "./__pycache__"
  - "__pycache__/"
  - "./__pycache__/"
  - "__pycache__/**"
  - "./__pycache__/**"
  - "**/__pycache__"
  - "**/__pycache__/"
  - "**/__pycache__/**"
  - "**/__pycache__/**/*"
  - "**/codeconcat.egg-info"
  - "**/codeconcat.egg-info/"
  - "**/codeconcat.egg-info/**"
  - "**/codeconcat.egg-info/**/*"

  # Documentation
  - "./docs"
  - "./docs/"
  - "./docs/**"
  - "./docs/**/*"
  - "**/docs/"
  - "**/docs/**"
  - "**/docs/**/*"
  - "./docs/_build"
  - "./docs/_build/"
  - "./docs/_build/**"
  - "**/docs/_build/"
  - "**/docs/_build/**"
  - "./_static"
  - "./_static/"
  - "./_static/**"
  - "**/_static/"
  - "**/_static/**"
  - "./_templates"
  - "./_templates/"
  - "./_templates/**"
  - "**/_templates/"
  - "**/_templates/**"

  # CodeConCat Output
  - "./code_concat_output.md"
  - "**/code_concat_output.md"
