"""Constants and shared configuration values for CodeConcat."""

from typing import List

# Default file patterns to exclude from processing
DEFAULT_EXCLUDE_PATTERNS: List[str] = [
    # Version Control
    ".git/",  # Match the .git directory itself
    ".git/**",  # Match contents of .git directory
    "**/.git/",  # Match .git directory anywhere in tree
    "**/.git/**",  # Match contents of .git directory anywhere in tree
    ".gitignore",
    "**/.gitignore",
    ".svn/",
    "**/.svn/",
    "**/.svn/**",
    ".hg/",
    "**/.hg/",
    "**/.hg/**",
    ".bzr/",
    "**/.bzr/",
    "**/.bzr/**",
    ".gitattributes",
    ".hgignore",
    ".svnignore",
    # CodeConcat configuration
    ".codeconcat.yml",
    # Dependencies and build artifacts
    "node_modules/",
    "**/node_modules/",
    "**/node_modules/**",
    "vendor/",
    "**/vendor/",
    "**/vendor/**",
    "bower_components/",
    "**/bower_components/",
    "**/bower_components/**",
    "__pycache__/",
    "**/__pycache__/",
    "**/__pycache__/**",
    "*.pyc",
    "**/*.pyc",
    "*.pyo",
    "**/*.pyo",
    "*.pyd",
    "**/*.pyd",
    ".Python",
    "build/",
    "**/build/",
    "**/build/**",
    "dist/",
    "**/dist/",
    "**/dist/**",
    "*.egg-info/",
    "**/*.egg-info/",
    "**/*.egg-info/**",
    "*.egg",
    "**/*.egg",
    # IDE and editor files
    ".vscode/",
    ".idea/",
    "*.swp",
    "*.swo",
    "*~",
    ".project",
    ".classpath",
    ".settings/",
    "*.sublime-project",
    "*.sublime-workspace",
    ".vim/",
    ".vimrc",
    # OS generated files
    ".DS_Store",
    "**/.DS_Store",
    "._*",
    "**/._*",
    ".Spotlight-V100",
    ".Trashes",
    "ehthumbs.db",
    "Thumbs.db",
    "**/Thumbs.db",
    "desktop.ini",
    # Testing and coverage
    ".coverage",
    ".pytest_cache/",
    "**/.pytest_cache/**",
    ".tox/",
    "nosetests.xml",
    "coverage.xml",
    "*.cover",
    ".hypothesis/",
    "htmlcov/",
    "coverage/",
    "**/coverage/",
    "**/coverage/**",
    ".phpunit.result.cache",
    # R specific
    ".Rcheck/",
    "**/.Rcheck/",
    "**/.Rcheck/**",
    ".Rhistory",
    "**/.Rhistory",
    ".RData",
    "**/.RData",
    # Next.js specific
    ".next/",
    "**/.next/",
    "**/.next/**",
    "**/static/chunks/**",
    "**/server/chunks/**",
    "**/BUILD_ID",
    "**/trace",
    "**/*.map",
    "**/webpack-*.js",
    "**/manifest*.js",
    "**/server-reference-manifest.js",
    "**/middleware-manifest.js",
    "**/client-reference-manifest.js",
    "**/webpack-runtime.js",
    "**/middleware-build-manifest.js",
    "**/middleware-react-loadable-manifest.js",
    "**/interception-route-rewrite-manifest.js",
    "**/next-font-manifest.js",
    "**/polyfills-*.js",
    "**/main-*.js",
    "**/framework-*.js",
    # Documentation
    "docs/_build/",
    "site/",
    # Environment files
    ".env",
    "**/.env",
    ".env.*",
    "**/.env.*",
    "venv/",
    "venv/**",
    "**/venv/",
    "**/venv/**",
    "*venv/",
    "*venv/**",
    "ENV/",
    "**/ENV/",
    "**/ENV/**",
    "env/",
    "**/env/",
    "**/env/**",
    # Logs
    "*.log",
    "logs/",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    # Package lock files
    "package-lock.json",
    "**/package-lock.json",
    "yarn.lock",
    "**/yarn.lock",
    "pnpm-lock.yaml",
    "**/pnpm-lock.yaml",
    "Gemfile.lock",
    "composer.lock",
    "poetry.lock",
    "Pipfile.lock",
    # Database files
    "*.sql",
    "*.sqlite",
    "*.db",
    # Temporary files
    "tmp/",
    "temp/",
    "*.tmp",
    "*.temp",
    "*.bak",
    "*.backup",
    "*.old",
    # Binary and media files
    "*.exe",
    "*.dll",
    "*.so",
    "*.dylib",
    "*.bin",
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.gif",
    "*.ico",
    "*.svg",
    "*.mp3",
    "*.mp4",
    "*.avi",
    "*.mov",
    "*.mkv",
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.xls",
    "*.xlsx",
    "*.ppt",
    "*.pptx",
    # Archive files
    "*.jar",
    "**/*.jar",
    "*.war",
    "**/*.war",
    "*.ear",
    "**/*.ear",
    "*.zip",
    "**/*.zip",
    "*.tar.gz",
    "**/*.tar.gz",
    "*.rar",
    "**/*.rar",
    # Cache directories
    ".cache/",
    "**/.cache/",
    "**/.cache/**",
    ".sass-cache/",
    ".parcel-cache/",
    "out/",
    # Test directories (can be uncommented if you want to exclude tests)
    # "tests/",
    # "**/tests/",
    # "**/tests/**",
    # "**/test/",
    # "**/test/**",
    # Common large directories
    "**/libs/**",
    "**/third_party/**",
    # Hidden files and directories (aggressive)
    "**/.*",  # All hidden files and directories
    "**/.*/",  # All hidden directories
    "**/.*/***",  # Contents of hidden directories
    # Security and secrets
    "*.pem",
    "*.key",
    "*.cert",
    "*.crt",
    ".secrets/",
    "secrets.yml",
    "secrets.json",
]

# File extensions considered as source code
SOURCE_CODE_EXTENSIONS = {
    # Programming languages
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".java",
    ".cpp",
    ".cc",
    ".cxx",
    ".c",
    ".h",
    ".hpp",
    ".cs",
    ".php",
    ".rb",
    ".go",
    ".rs",
    ".swift",
    ".kt",
    ".scala",
    ".r",
    ".jl",
    ".lua",
    ".pl",
    ".sh",
    ".bash",
    # Markup and config
    ".html",
    ".htm",
    ".xml",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    # Web technologies
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".vue",
    ".svelte",
    # Documentation
    ".md",
    ".rst",
    ".txt",
}

# Maximum file size for processing (in bytes)
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB

# Maximum total project size (in bytes)
MAX_PROJECT_SIZE = 100 * 1024 * 1024  # 100 MB

# Token limits for different models
TOKEN_LIMITS = {
    # OpenAI GPT models
    "gpt-3.5-turbo": 16385,
    "gpt-4": 8192,
    "gpt-4-32k": 32768,
    "gpt-4-turbo": 128000,
    "gpt-4o": 128000,
    "gpt-4o-mini": 128000,
    "o1": 200000,
    "o1-mini": 128000,
    "text-davinci-003": 4097,
    # Anthropic Claude models
    "claude": 100000,
    "claude-2": 100000,
    "claude-2.1": 200000,
    "claude-3": 200000,
    "claude-3-opus": 200000,
    "claude-3-sonnet": 200000,
    "claude-3-haiku": 200000,
    "claude-3.5-sonnet": 200000,
    "claude-3.5-haiku": 200000,
    # Google Gemini models
    "gemini-1.5-pro": 1000000,
    "gemini-1.5-flash": 1000000,
    # Default fallback
    "default": 100000,
}

# Compression levels and their settings
COMPRESSION_SETTINGS = {
    "low": {
        "importance_threshold": 0.25,
        "context_lines": 2,
        "min_segment_size": 5,
    },
    "medium": {
        "importance_threshold": 0.5,
        "context_lines": 1,
        "min_segment_size": 3,
    },
    "high": {
        "importance_threshold": 0.75,
        "context_lines": 0,
        "min_segment_size": 1,
    },
    "aggressive": {
        "importance_threshold": 0.9,
        "context_lines": 0,
        "min_segment_size": 1,
    },
}

# Security scan patterns
SECURITY_PATTERNS = {
    "high_risk_functions": [
        "exec",
        "eval",
        "system",
        "popen",
        "subprocess",
        "os.system",
        "child_process",
        "shellexec",
        "wscript.shell",
    ],
    "sql_keywords": [
        "SELECT",
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "CREATE",
        "ALTER",
        "TRUNCATE",
        "UNION",
    ],
    "crypto_functions": [
        "md5",
        "sha1",
        "des",
        "rc4",
        "ecb",
    ],
}
